name: AccessibilityCheck
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pa11y-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install dependencies
        run: |
          npm install
          npm install -g pa11y-ci@latest

      - name: Build
        run: npm run build

      - name: Run Pa11y tests
        run: |
          npm run preview -- --host &
          sleep 5
          pa11y-ci --config=pa11yci.json --json > pa11y-result.json || true

      - name: Display Pa11y results
        run: |
          echo "=== Pa11y Test Results ==="
          echo "Total tests: $(jq '.total' pa11y-result.json)"
          echo "Passes: $(jq '.passes' pa11y-result.json)"
          echo "Errors: $(jq '.errors' pa11y-result.json)"
          echo -e "\n=== Detailed Errors ==="
          jq -r '.results | to_entries[] | .value[] | "Error: \(.message)\nLocation: \(.selector)\nContext: \(.context)\n---"' pa11y-result.json