name: AccessibilityCheck
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pa11y-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm
      - name: Install dependencies
        run: |
          npm install
          npm install -g pa11y-ci
      - name: Build
        run: npm run build
      - name: pa11y-ci
        run: npm run preview & sleep 3; pa11y-ci
      - name: Post result to GoogleSpreadSheet via GoogleSpreadSheet
        env:
          GAS_WEBHOOK_URL: ${{ secrets.GAS_WEBHOOK_URL }}
        run: |
          curl -X POST "$GAS_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d @pa11y-result.json